
version: '3.2'

services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}-ce.0
    restart: always
    hostname: gitlab
    volumes:
      - ./volumes/gitlab-ce/config:/etc/gitlab:Z
      - ./volumes/gitlab-ce/logs:/var/log/gitlab:Z
      - ./volumes/gitlab-ce/data:/var/opt/gitlab:Z
    ports:
      - 443:443
      - 1000:80
      - 22:22
      - 4567:4567
    depends_on:
      - redis
      - postgres

  gitlab-runner1:
    image: gitlab/gitlab-runner:alpine-v${GITLAB_RUNNER_VERSION}
    restart: always
    volumes:
      - ./volumes/gitlab-runner1:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock

  #~ gitlab-runner2:
    #~ image: gitlab/gitlab-runner:alpine-v${GITLAB_RUNNER_VERSION}
    #~ volumes:
      #~ - ./gitlab-runner2:/etc/gitlab-runner:Z
      #~ - /var/run/docker.sock:/var/run/docker.sock

  #~ gitlab-runner3:
    #~ image: gitlab/gitlab-runner:alpine-v${GITLAB_RUNNER_VERSION}
    #~ volumes:
      #~ - ./gitlab-runner3:/etc/gitlab-runner:Z
      #~ - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    command:
      - --loglevel warning
    volumes:
      - ./volumes/redis:/var/lib/redis
    restart: always
